### ISSUE TITLE
split flit-core to its own feedstock for bootstrapping

### ISSUE THREAD

**Issue by beckermr** [conda-forge/flit-feedstock#38]
As far as I can tell right now 

 - `wheel` [depends on `flit-core`](https://github.com/conda-forge/wheel-feedstock/blob/main/recipe/meta.yaml#L20) 
 - in order build `flit-core`, we have to also build `flit` in the same recipe 
 - `flit` depends on packages like requests with [complex dependencies](https://github.com/conda-forge/requests-feedstock/blob/main/recipe/meta.yaml#L22)

I am pretty sure this situation creates a non-trivial bootstrapping issue, especially with respect to python migrations. It certainly [confuses the bot](https://github.com/regro/cf-scripts/issues/2275).

Can we split `flit-core` into its own feedstock?

cc @jakirkham @conda-forge/core for guidance

**Comment by takluyver** [comment]
That probably makes sense if conda is bootstrapping Python packaging tools 'properly' (i.e. without relying on pip fetching & installing build dependencies for some packages). I'm fairly out of the loop on conda packaging these days, but I'm happy to look over something if you want to do it.

**Comment by takluyver** [comment]
Bootstrapping docs, in case you haven't already seen them: https://flit.pypa.io/en/stable/bootstrap.html

**Comment by beckermr** [comment]
xref staged-recipes https://github.com/conda-forge/staged-recipes/pull/25847
xref feedstock-outputs https://github.com/conda-forge/feedstock-outputs/pull/62
